url: https://subhankarghosh.com
title: Subhankar Ghosh
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: subhankar94
github_username: subhankar94

authors:
  subhankar:
    name: Subhankar Ghosh
